// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO7XTuu6Fuvtj_6MgdjHojtRiy1qyPdH4',
    appId: '1:355509414488:web:a9e07dcee64869c338382d',
    messagingSenderId: '355509414488',
    projectId: 'task-3-sms-registration',
    authDomain: 'task-3-sms-registration.firebaseapp.com',
    storageBucket: 'task-3-sms-registration.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVtuxp1wvxGniF0xq62HtkNWcRg-T28Q',
    appId: '1:355509414488:android:608091551bf33f0a38382d',
    messagingSenderId: '355509414488',
    projectId: 'task-3-sms-registration',
    storageBucket: 'task-3-sms-registration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQftL2kdby-EN8nHuPBp1xxGSrZZqvvVk',
    appId: '1:355509414488:ios:4a5f91524a0b2fcf38382d',
    messagingSenderId: '355509414488',
    projectId: 'task-3-sms-registration',
    storageBucket: 'task-3-sms-registration.appspot.com',
    iosBundleId: 'com.example.formRegistration',
  );
}
